### ISSUE TITLE
error: a parse error occurs in JSX within the render function

### ISSUE THREAD

**Issue by zavierkolten** [g-plane/swc-plugin-vue-jsx#11]
**repo:** https://github.com/zavierkolten/bundler-compare/tree/jsx
**branch:** jsx

```
pnpm i

pnpm r-dev
```

<img width="390" alt="image" src="https://github.com/user-attachments/assets/29a66c82-dffb-49eb-b281-a8e5f1caa3c1">

<img width="881" alt="image" src="https://github.com/user-attachments/assets/9d6b8348-e0d9-4cf1-98f9-ef6e6cdbbf95">

in `rspack.config.js`，using babel will work as expected

<img width="539" alt="image" src="https://github.com/user-attachments/assets/b185ea07-0f36-43ad-82cf-c3beaf533270">

**Comment by g-plane** [comment]
There should be a wrong configuration of your bundler, not this plugin.
