### ISSUE TITLE
Cryptic error.

### ISSUE THREAD

**Issue by rotexhawk** [g-plane/swc-plugin-vue-jsx#5]
thread '<unnamed>' panicked at 'invalid utf8 character detected: FromUtf8Error { bytes: [

Maybe an issue with i18n? 

const i18n = createI18n({ legacy: false });

{{ $t('savedsearchform.instantly') }}

**Comment by g-plane** [comment]
Please provide more detail.

**Comment by rotexhawk** [comment]
hidden

**Comment by g-plane** [comment]
With the code you gave, I don't think it's related to this plugin, because you even didn't use JSX.

**Comment by rotexhawk** [comment]
I am new to vue. Do you know if there is a way to run vue tests with swc-jest. I use ts-jest and it is very slow.

**Comment by g-plane** [comment]
Sorry I don't know. You can ask others.
