### ISSUE TITLE
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("H:\\syc-eds-front\\src\\views\\Bus\\component\\NodeState\\index.jsx")'

### ISSUE THREAD

**Issue by baiyuze** [g-plane/swc-plugin-vue-jsx#6]
![image](https://github.com/g-plane/swc-plugin-vue-jsx/assets/27543832/b0377691-5ac7-4ada-aaf2-3bc1606531cd)

![image](https://github.com/g-plane/swc-plugin-vue-jsx/assets/27543832/fb6952ba-5529-47ec-a4bd-1d1240bfe9d2)

The .swcrc configuration is as follows
```json
{
    "isModule": true,
    "sourceMaps": true,
    "inlineSourcesContent": true,
    "jsc": {
        "target": "esnext",
        "parser": {
          "syntax": "ecmascript",
          "jsx": true,
          "dynamicImport": true,
          "privateMethod": true,
          "functionBind": true,
          "exportDefaultFrom": true,
          "exportNamespaceFrom": true,
          "decorators": true,
          "decoratorsBeforeExport": true,
          "topLevelAwait": true,
          "importMeta": true
        },
        "experimental": {
          "plugins": [["swc-plugin-vue-jsx", {
            "transformOn": true,
            "optimize": true
          }]]
        }
    }
  }
```
```js
    "swc-loader": "^0.2.3",
    "swc-plugin-vue-jsx": "^0.2.5",
    "@swc/core": "^1.3.80"
```

An error is reported when the relevant route is encountered

**Comment by g-plane** [comment]
You may need to downgrade SWC to solve this temporarily.

**Comment by baiyuze** [comment]
> 您可能需要降级 SWC 来暂时解决此问题。

大概是多少版本呢？

**Comment by baiyuze** [comment]
How many versions are there?

1.3.68？

**Comment by g-plane** [comment]
I'm not sure. You can try those released two or three months ago.

**Comment by baiyuze** [comment]
![image](https://github.com/g-plane/swc-plugin-vue-jsx/assets/27543832/9d323222-939b-485c-8729-7cbe9c089646)
I downgrade to 1.3.68 and get an error UFT8, as shown in the figure

**Comment by g-plane** [comment]
Are you sure this is occurred by this plugin? You can check this by removing this plugin.

**Comment by baiyuze** [comment]
I used rspack to call swc-loader

**Comment by g-plane** [comment]
You can remove plugin by modifying your SWC configuration.

**Comment by baiyuze** [comment]
I'll fork the warehouse, see if I can figure it out

**Comment by g-plane** [comment]
I can't reproduce with latest SWC version. Maybe this has been fixed. I'll release a new plugin version later and please upgrade SWC (`@swc/core`) and this plugin to latest.

**Comment by loilo** [comment]
Unfortunately, this problem re-appears when updating `@swc/core` from 1.3.105 to 1.3.106.

**Comment by g-plane** [comment]
You should upgrade to latest SWC. Also, don't reply in closed issue.

**Comment by loilo** [comment]
Latest SWC 1.3.107 still has this problem. Should I open a new issue?

**Comment by g-plane** [comment]
Yes.

**Comment by loilo** [comment]
Sorry for replying again – no new issue is needed. The 0.3.0 version of this plugin you just released today fixes this issue again. Sorry for bothering!
